###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
#    memcached:
#        image: 'memcached:alpine'

#    redis:
#        image: 'redis:alpine'

    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=app
        ports:
            - '44004:5432'

#    clickhouse:
#        image: 'clickhouse/clickhouse-server:latest'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '44000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
